name: forrestthedev-html
static_sites:
  - environment_slug: html
    github:
      branch: main
      deploy_on_push: true
      repo: Forrest22/forrestthedev
    name: forrestthedev
    source_dir: dist
    output_dir: dist
    build_command: "" # No build command, build should be done before committing.
